"""Compile Gurobi solver output into a deterministic TypeScript artifact.

The runtime is a static SPA and cannot host Gurobi, so the solver runs at
build time and its frozen, fingerprinted output is shipped as a typed module.

    python3 tools/gurobi/generate_ts.py
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(__file__)
ROOT = os.path.dirname(os.path.dirname(HERE))
ALLOCATION = os.path.join(HERE, "out", "allocation.json")
SCHEDULE = os.path.join(HERE, "out", "schedule.json")
TARGET = os.path.join(ROOT, "src", "generated", "solver-artifacts.ts")


def load(path: str) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def main() -> None:
    allocation = load(ALLOCATION)
    schedule = load(SCHEDULE)

    version = ".".join(str(v) for v in allocation["solver"]["version"]) if isinstance(allocation["solver"]["version"], list) else allocation["solver"]["version"]

    lines = [
        "// AUTO-GENERATED by tools/gurobi/generate_ts.py — DO NOT EDIT BY HAND.",
        f"// Solver: Gurobi {version}, seed {allocation['solver']['seed']}, threads {allocation['solver']['threads']} (deterministic).",
        "// Regenerate with: python3 tools/gurobi/allocate_leaktests.py && python3 tools/gurobi/schedule.py && python3 tools/gurobi/generate_ts.py",
        "",
        f"export const SOLVER = {json.dumps(allocation['solver'], sort_keys=True, indent=2)} as const;",
        "",
        f"export const LEAKTEST_BASELINE = {json.dumps(allocation['baseline'], sort_keys=True, indent=2)} as const;",
        "",
        f"export const LEAKTEST_RECOVERY = {json.dumps(allocation['recovery'], sort_keys=True, indent=2)} as const;",
        "",
        f"export const PRODUCTION_SCHEDULE = {json.dumps(schedule, sort_keys=True, indent=2)} as const;",
        "",
    ]
    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {os.path.relpath(TARGET, ROOT)}")


if __name__ == "__main__":
    main()